name: mol2image
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - gunicorn
  - scipy
  - numpy
  - tqdm
  - tensorboardx
  - flask
  - scikit-learn
  - hyperopt
  - rdkit
  - cudatoolkit
  - torchvision
  - pytorch
  - gulpio

test blabla
